Repository Team-Growthook/Growthook-Server, pull requests merged in 2023-12, with the labels that each got.

#6 [SETTING]Swagger 기초 세팅
  growthookServer/.gitignore
  growthookServer/build.gradle
  growthookServer/src/main/java/com/example/growthookserver/api/HealthCheckController.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/SwaggerConfig.java
Labels: ⚙️ SETTING ⚙️, 홍준

#22 #16 [FEAT] 씨앗 생성 API 개발
  growthookServer/src/main/java/com/example/growthookserver/api/cave/controller/CaveController.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/repository/CaveRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/service/Impl/CaveServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/repository/MemberRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/domain/Seed.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/dto/request/SeedCreateRequestDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/dto/response/SeedCreateResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 예슬

#25 [FEAT] 엑션 플랜 생성 API 개발
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/controller/ActionPlanController.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/domain/ActionPlan.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/request/ActionPlanCreateRequestDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/ActionPlanCreateResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/repository/ActionPlanRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/service/ActionPlanService.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/service/Impl/ActionPlanServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 홍준

#40 #18 [FEAT] 씨앗 수정 API 개발
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/domain/Seed.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/dto/request/SeedUpdateRequestDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 예슬

#44 #43 [FIX] swagger 버전 통합
  growthookServer/build.gradle
  growthookServer/src/main/java/com/example/growthookserver/common/config/SwaggerConfig.java
Labels: 🔨 FIX 🔨, 예슬
