Repository Team-Growthook/Growthook-Server, pull requests merged in 2024-01, with the labels that each got.

#46 [FEAT]씨앗 알림 조회 API개발
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/dto/response/SeedAlarmGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 홍준

#55 [FEAT] 보관함별 인사이트 리스트 조회 API 개발
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/dto/response/SeedListByCaveGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 예슬

#56 [FEAT] 전체 씨앗 리스트 조회 API
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/dto/response/SeedListGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 예슬

#57 [FEAT] 씨앗 스크랩 상태 토글 API
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/domain/Seed.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 예슬

#58 [FEAT] 씨앗 잠금 해제 API
  growthookServer/src/main/java/com/example/growthookserver/api/member/domain/Member.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/domain/Seed.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/SeedService.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 예슬

#73 [FIX]액션 플랜 조회 시 리뷰가 달린 액션플랜인지 포함하여 반환
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/ActionPlanGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/DoingActionPlanGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/FinishedActionPlanGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/service/Impl/ActionPlanServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/review/repository/ReviewRepository.java
Labels: ♻️ REFACTOR ♻️ , 홍준

#75 [FEAT]액션 플랜 스크랩 토글 기능 API
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/controller/ActionPlanController.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/domain/ActionPlan.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/service/ActionPlanService.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/service/Impl/ActionPlanServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/SuccessStatus.java
Labels: ✨ FEAT ✨, 홍준

#78 [FIX] 동굴 이미지 인덱스도 내려주도록 수정
  growthookServer/src/main/java/com/example/growthookserver/api/cave/domain/Cave.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/dto/response/CaveAllResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/dto/response/CaveCreateResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/repository/CaveRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/service/Impl/CaveServiceImpl.java
Labels: 🔨 FIX 🔨, 예슬

#81 [FEAT] 카카오 소셜 로그인 + JWT 인증
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/controller/ActionPlanController.java
  growthookServer/src/main/java/com/example/growthookserver/api/cave/controller/CaveController.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/controller/AuthController.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/dto/Request/AuthRequestDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/dto/Response/AuthResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/dto/Response/AuthTokenResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/dto/SocialInfoDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/service/AuthService.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/service/Impl/AuthServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/service/KakaoAuthService.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/controller/MemberController.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/domain/Member.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/repository/MemberRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/review/controller/ReviewController.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/controller/SeedController.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/SecurityConfig.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/SwaggerConfig.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/jwt/JwtAuthenticationEntryPoint.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/jwt/JwtAuthenticationFilter.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/jwt/JwtExceptionType.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/jwt/JwtTokenProvider.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/jwt/UserAuthentication.java
Labels: ✨ FEAT ✨, 예슬

#83 [FEAT] 애플 소셜 로그인 개발
  growthookServer/build.gradle
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/dto/Request/AuthRequestDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/service/AppleAuthService.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/auth/service/Impl/AuthServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/common/response/ErrorStatus.java
Labels: ✨ FEAT ✨, 예슬

#87 [FIX] 회원 정보 조회 시, 프로필 이미지 url도 내려주도록 수정
  growthookServer/src/main/java/com/example/growthookserver/api/member/dto/response/MemberDetailGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/member/service/MemberServiceImpl.java
Labels: 🔨 FIX 🔨, 예슬

#88 [FIX] 목표 기간이 지나면 씨앗 잠기도록 스케줄링 구현
  growthookServer/build.gradle
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/ActionPlanGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/DoingActionPlanGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/actionplan/dto/response/FinishedActionPlanGetResponseDto.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/repository/SeedRepository.java
  growthookServer/src/main/java/com/example/growthookserver/api/seed/service/Impl/SeedServiceImpl.java
  growthookServer/src/main/java/com/example/growthookserver/common/config/TimeConfig.java
  growthookServer/src/main/java/com/example/growthookserver/common/util/SeedScheduler.java
Labels: 🔨 FIX 🔨, 예슬
